from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from jinja2 import Template

from bountyhunt.modules.notify import DiffSummary

T_HEAD = """# Bountyhunt Scan Report

**Generated:** {{ generated_at }}

## Overview

- **Total unique hosts:** {{ hosts|length }}
- **Total scan runs:** {{ scan_runs|length }}
- **Total findings:** {{ findings|length }}
- **Total endpoints:** {{ endpoints|length }}
- **Total secrets (redacted):** {{ secrets|length }}
- **Last scan:** {{ last_scan }}

## Scan Runs

| # | Timestamp | Module | Target | Status |
|---|-----------|--------|--------|--------|
"""
T_RUNS = "{% for run in scan_runs %}| {{ run.id }} | {{ run.timestamp }} | {{ run.module }} | {{ run.target }} | {{ run.status }} |\n{% endfor %}\n\n"  # noqa: E501
T_HOSTS_HEADER = "## Hosts\n\n| Domain | IP | Status | Title | Tech | Web Server | First Seen | Last Seen |\n|--------|----|--------|-------|------|------------|------------|-----------|\n"  # noqa: E501
T_HOSTS = "{% for host in hosts %}| {{ host.domain }} | {{ host.ip or '' }} | {{ host.status_code or '' }} | {{ host.title or '' }} | {{ host.tech or '' }} | {{ host.webserver or '' }} | {{ host.first_seen }} | {{ host.last_seen }} |\n{% endfor %}\n"  # noqa: E501
T_FINDINGS = """
## Potential Findings — Manual Verification Required

> **Automated scan results require manual verification before reporting.**
> This section lists potential security findings detected by automated tools.
> They may include false positives. Do not report findings directly from this
> report without manual triage and confirmation.

| Host | Template | Name | Severity | Matched At |
|------|----------|------|----------|------------|
{% for f in findings %}| {{ f.host }} | {{ f.template_id }} | {{ f.name or '' }} |\
 {{ f.severity or '' }} | {{ f.matched_at or '' }} |
{% endfor %}
"""
T_ENDPOINTS = """
## Discovered Endpoints

| URL | Host | Status | Content Length | Content Type |
|-----|------|--------|----------------|--------------|
{% for e in endpoints %}| {{ e.url }} | {{ e.host }} | {{ e.status_code or '' }} \
| {{ e.content_length or '' }} | {{ e.content_type or '' }} |
{% endfor %}
"""
T_SECRETS = """
## Secrets Found (Redacted)

> **Only redacted values are shown.**
> These are potential secrets detected by automated regex patterns and
> require manual verification. Do not report them without confirmation.

| Host | URL | Type | Redacted Value |
|------|-----|------|----------------|
{% for s in secrets %}| {{ s.host }} | {{ s.url }} | {{ s.pattern_type }} | ``{{ s.redacted }}`` |
{% endfor %}
"""
T_DIFF_BASELINE = """
*Baseline run — no prior scan to compare.  Run a second scan to see diff.*
"""
T_DIFF_NONE = """
*No new findings since last scan.*
"""
T_DIFF_HOSTS = """
### New Hosts

| Domain | IP | Status | Title |
|--------|----|--------|-------|
{% for h in diff.hosts %}| {{ h.get('domain', h.get('host', '?')) }} \
| {{ h.get('ip', '') }} | {{ h.get('status_code', '') }} | {{ h.get('title', '') }} |
{% endfor %}
"""
T_DIFF_PORTS = """
### New Ports

| Host | Port | Protocol |
|------|------|----------|
{% for p in diff.ports %}| {{ p.host }} | {{ p.port }} | {{ p.get('protocol', 'tcp') }} |
{% endfor %}
"""
T_DIFF_FINDINGS = """
### New Findings

| Host | Template | Name | Severity |
|------|----------|------|----------|
{% for f in diff.findings %}| {{ f.host }} | {{ f.template_id }} \
| {{ f.get('name', '') }} | {{ f.get('severity', '') }} |
{% endfor %}
"""
T_DIFF_SECRETS = """
### New Secrets (Redacted)

| Host | URL | Type | Value |
|------|-----|------|-------|
{% for s in diff.secrets %}| {{ s.host }} | {{ s.url }} | {{ s.pattern_type }} | ``{{ s.redacted }}`` |
{% endfor %}
"""
T_DIFF_ENDPOINTS = """
### New Endpoints

| URL | Status |
|-----|--------|
{% for e in diff.endpoints %}| {{ e.url }} | {{ e.get('status_code', '') }} |
{% endfor %}
"""

T_FOOTER = "\n---\n\n*Report generated by [bountyhunt](https://github.com/bess1lie/bountyhunt)*\n"


def generate_report(
    hosts: List[Dict[str, Any]],
    scan_runs: List[Dict[str, Any]],
    output_path: Path,
    fmt: str = "markdown",
    findings: Optional[List[Dict[str, Any]]] = None,
    endpoints: Optional[List[Dict[str, Any]]] = None,
    secrets: Optional[List[Dict[str, Any]]] = None,
    diff: Optional[DiffSummary] = None,
) -> None:
    if findings is None:
        findings = []
    if endpoints is None:
        endpoints = []
    if secrets is None:
        secrets = []
    if fmt == "markdown":
        _generate_markdown(hosts, scan_runs, findings, endpoints, secrets, diff, output_path)
    elif fmt == "html":
        _generate_html(hosts, scan_runs, findings, endpoints, secrets, diff, output_path)
    else:
        raise ValueError(f"Unsupported format: {fmt}")


def _render_diff_templates(diff: Optional[DiffSummary]) -> str:
    """Build the diff section of the report.

    Reuses ``DiffSummary`` (same dataclass as ``monitor.py``) — no
    duplicated diff logic.
    """
    if diff is None:
        return ""
    if diff.is_baseline:
        return render_jinja(T_DIFF_BASELINE, diff=diff)
    if not diff.has_items:
        return render_jinja(T_DIFF_NONE, diff=diff)

    parts = [render_jinja(T_DIFF_HOSTS, diff=diff)]
    if diff.ports:
        parts.append(render_jinja(T_DIFF_PORTS, diff=diff))
    if diff.findings:
        parts.append(render_jinja(T_DIFF_FINDINGS, diff=diff))
    if diff.secrets:
        parts.append(render_jinja(T_DIFF_SECRETS, diff=diff))
    if diff.endpoints:
        parts.append(render_jinja(T_DIFF_ENDPOINTS, diff=diff))
    return "\n".join(parts)


def render_jinja(template_str: str, **kwargs) -> str:
    return Template(template_str).render(**kwargs)


def _generate_markdown(
    hosts: List[Dict[str, Any]],
    scan_runs: List[Dict[str, Any]],
    findings: List[Dict[str, Any]],
    endpoints: List[Dict[str, Any]],
    secrets: List[Dict[str, Any]],
    diff: Optional[DiffSummary],
    output_path: Path,
) -> None:
    diff_html = _render_diff_templates(diff)
    full_template = (
        T_HEAD
        + T_RUNS
        + T_HOSTS_HEADER
        + T_HOSTS
        + T_FINDINGS
        + T_ENDPOINTS
        + T_SECRETS
        + ("## Changes Since Last Scan\n" if diff else "")
        + diff_html
        + T_FOOTER
    )
    template = Template(full_template)
    content = template.render(
        hosts=hosts,
        scan_runs=scan_runs,
        findings=findings,
        endpoints=endpoints,
        secrets=secrets,
        diff=diff or DiffSummary(target="", scan_timestamp=""),
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
        last_scan=scan_runs[0]["timestamp"] if scan_runs else "N/A",
    )
    output_path.write_text(content)


def _generate_html(
    hosts: List[Dict[str, Any]],
    scan_runs: List[Dict[str, Any]],
    findings: List[Dict[str, Any]],
    endpoints: List[Dict[str, Any]],
    secrets: List[Dict[str, Any]],
    diff: Optional[DiffSummary],
    output_path: Path,
) -> None:
    html_template = Template("""<!DOCTYPE html>
<html>
<head><title>Bountyhunt Report</title>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 2em; }
table { border-collapse: collapse; width: 100%; }
th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
th { background: #f5f5f5; }
tr:nth-child(even) { background: #f9f9f9; }
h1 { color: #333; }
blockquote { border-left: 4px solid #e74c3c; margin: 1em 0; padding: 0.5em 1em; background: #fdf2f2; }
code { background: #f4f4f4; padding: 1px 4px; border-radius: 3px; }
</style></head>
<body>
<h1>Bountyhunt Scan Report</h1>
<p><strong>Generated:</strong> {{ generated_at }}</p>
<h2>Overview</h2>
<ul>
<li><strong>Total unique hosts:</strong> {{ hosts|length }}</li>
<li><strong>Total scan runs:</strong> {{ scan_runs|length }}</li>
<li><strong>Total findings:</strong> {{ findings|length }}</li>
<li><strong>Total endpoints:</strong> {{ endpoints|length }}</li>
<li><strong>Total secrets (redacted):</strong> {{ secrets|length }}</li>
<li><strong>Last scan:</strong> {{ last_scan }}</li>
</ul>
<h2>Hosts</h2>
<table>
<tr>
<th>Domain</th><th>IP</th><th>Status</th><th>Title</th>
<th>Tech</th><th>Web Server</th><th>First Seen</th><th>Last Seen</th>
</tr>
{% for host in hosts %}
<tr>
<td>{{ host.domain }}</td><td>{{ host.ip or '' }}</td><td>{{ host.status_code or '' }}</td>
<td>{{ host.title or '' }}</td><td>{{ host.tech or '' }}</td><td>{{ host.webserver or '' }}</td>
<td>{{ host.first_seen }}</td><td>{{ host.last_seen }}</td>
</tr>
{% endfor %}
</table>
<h2>Potential Findings &mdash; Manual Verification Required</h2>
<blockquote>
Automated scan results require manual verification before reporting.
This section lists potential security findings detected by automated tools.
They may include false positives. Do not report findings directly from this
report without manual triage and confirmation.
</blockquote>
<table>
<tr>
<th>Host</th><th>Template</th><th>Name</th><th>Severity</th><th>Matched At</th>
</tr>
{% for f in findings %}
<tr>
<td>{{ f.host }}</td><td>{{ f.template_id }}</td><td>{{ f.name or '' }}</td>
<td>{{ f.severity or '' }}</td><td>{{ f.matched_at or '' }}</td>
</tr>
{% endfor %}
</table>
<h2>Discovered Endpoints</h2>
<table>
<tr>
<th>URL</th><th>Host</th><th>Status</th><th>Content Length</th><th>Content Type</th>
</tr>
{% for e in endpoints %}
<tr>
<td>{{ e.url }}</td><td>{{ e.host }}</td><td>{{ e.status_code or '' }}</td>
<td>{{ e.content_length or '' }}</td><td>{{ e.content_type or '' }}</td>
</tr>
{% endfor %}
</table>
<h2>Secrets Found (Redacted)</h2>
<blockquote>
Only redacted values are shown. These are potential secrets detected by
automated regex patterns and require manual verification. Do not report
them without confirmation.
</blockquote>
<table>
<tr>
<th>Host</th><th>URL</th><th>Type</th><th>Redacted Value</th>
</tr>
{% for s in secrets %}
<tr>
<td>{{ s.host }}</td><td>{{ s.url }}</td><td>{{ s.pattern_type }}</td>
<td><code>{{ s.redacted }}</code></td>
</tr>
{% endfor %}
</table>
{% if diff %}
<h2>Changes Since Last Scan</h2>
{% if diff.is_baseline %}
<p><em>Baseline run — no prior scan to compare. Run a second scan to see diff.</em></p>
{% elif not diff.has_items %}
<p><em>No new findings since last scan.</em></p>
{% else %}
{% if diff.hosts %}
<h3>New Hosts</h3>
<table>
<tr><th>Domain</th><th>IP</th><th>Status</th><th>Title</th></tr>
{% for h in diff.hosts %}<tr><td>{{ h.get('domain', h.get('host', '?')) }}</td>\
<td>{{ h.get('ip', '') }}</td><td>{{ h.get('status_code', '') }}</td>\
<td>{{ h.get('title', '') }}</td></tr>{% endfor %}
</table>
{% endif %}
{% if diff.ports %}
<h3>New Ports</h3>
<table>
<tr><th>Host</th><th>Port</th><th>Protocol</th></tr>
{% for p in diff.ports %}<tr><td>{{ p.host }}</td><td>{{ p.port }}</td>\
<td>{{ p.get('protocol', 'tcp') }}</td></tr>{% endfor %}
</table>
{% endif %}
{% if diff.findings %}
<h3>New Findings</h3>
<table>
<tr><th>Host</th><th>Template</th><th>Name</th><th>Severity</th></tr>
{% for f in diff.findings %}<tr><td>{{ f.host }}</td>\
<td>{{ f.template_id }}</td><td>{{ f.get('name', '') }}</td>\
<td>{{ f.get('severity', '') }}</td></tr>{% endfor %}
</table>
{% endif %}
{% if diff.secrets %}
<h3>New Secrets (Redacted)</h3>
<table>
<tr><th>Host</th><th>URL</th><th>Type</th><th>Redacted Value</th></tr>
{% for s in diff.secrets %}<tr><td>{{ s.host }}</td><td>{{ s.url }}</td>\
<td>{{ s.pattern_type }}</td><td><code>{{ s.redacted }}</code></td></tr>{% endfor %}
</table>
{% endif %}
{% if diff.endpoints %}
<h3>New Endpoints</h3>
<table>
<tr><th>URL</th><th>Status</th></tr>
{% for e in diff.endpoints %}<tr><td>{{ e.url }}</td><td>{{ e.get('status_code', '') }}</td></tr>{% endfor %}
</table>
{% endif %}
{% endif %}
{% endif %}
</body></html>""")

    content = html_template.render(
        hosts=hosts,
        scan_runs=scan_runs,
        findings=findings,
        endpoints=endpoints,
        secrets=secrets,
        diff=diff,
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
        last_scan=scan_runs[0]["timestamp"] if scan_runs else "N/A",
    )
    output_path.write_text(content)
